exports.dbConfig={
    server:"LAPTOP-P4D7V446\\SQLEXPRESS",
    database:"INTERNSHIP",
    user:"sourish",
    password:"sourish@123",
    port:1433
};
exports.httpMsgsFormat="HTML";
exports.webPort=5000;